// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALyJdiStGB4GjyCYFkONzpQGbxVaTB6XE',
    appId: '1:143092725538:web:202af37400ffb58394d77b',
    messagingSenderId: '143092725538',
    projectId: 'aimelive-app',
    authDomain: 'aimelive-app.firebaseapp.com',
    storageBucket: 'aimelive-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXWF34nS_5jl3dcUrV5WqChcqWXyqRSk',
    appId: '1:143092725538:android:0c4057b92fbd42d594d77b',
    messagingSenderId: '143092725538',
    projectId: 'aimelive-app',
    storageBucket: 'aimelive-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IAb20kEsmwRtQlgIp-gO9xTdIgMEAkQ',
    appId: '1:143092725538:ios:73e5840f8d82e39e94d77b',
    messagingSenderId: '143092725538',
    projectId: 'aimelive-app',
    storageBucket: 'aimelive-app.appspot.com',
    iosClientId: '143092725538-9s9u2l4vjm1a9ur9kn08o847i7tkftm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimeliveApp',
  );
}
